apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  labels:
    app: {{ .Values.labels.app }}
    environment: {{ .Values.global.labels.environment}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl 
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}